# => Collection: cohesity.dataprotect
# =>
# => Start a protection job run.
---
- hosts: workstation
  gather_facts: false
  collections:
    - cohesity.dataprotect
  tasks:
    - name: Start Protection job
      cohesity_job:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: "started"
        name: "DemoJob"
        environment: "VMware"
